-- AlterTable
ALTER TABLE "ads" ALTER COLUMN "cover_img" SET DATA TYPE VARCHAR(384);

-- AlterTable
ALTER TABLE "pictures" ALTER COLUMN "picture_1" SET DATA TYPE VARCHAR(384),
ALTER COLUMN "picture_2" SET DATA TYPE VARCHAR(384),
ALTER COLUMN "picture_3" SET DATA TYPE VARCHAR(384),
ALTER COLUMN "picture_4" SET DATA TYPE VARCHAR(384),
ALTER COLUMN "picture_5" SET DATA TYPE VARCHAR(384),
ALTER COLUMN "picture_6" SET DATA TYPE VARCHAR(384);
